//#include "nodetypes.h"
#define STRING(x) #x
char *node_string[26] = {
    STRING(PROGRAM),
    STRING(GLOBAL_LIST),
    STRING(GLOBAL), //useless, use single child
    STRING(STATEMENT_LIST),
    STRING(PRINT_LIST), //list, flatten
    STRING(EXPRESSION_LIST),
    STRING(VARIABLE_LIST),
    STRING(ARGUMENT_LIST),
    STRING(PARAMETER_LIST),
    STRING(DECLARATION_LIST),
    STRING(FUNCTION),
    STRING(STATEMENT), //useless, use single child
    STRING(BLOCK),
    STRING(ASSIGNMENT_STATEMENT),
    STRING(RETURN_STATEMENT),
    STRING(PRINT_STATEMENT), //keep?
    STRING(NULL_STATEMENT),
    STRING(IF_STATEMENT),
    STRING(WHILE_STATEMENT),
    STRING(EXPRESSION), //remove if data == ""
    STRING(RELATION), 
    STRING(DECLARATION),
    STRING(PRINT_ITEM), //useless, use single child
    STRING(IDENTIFIER_DATA),
    STRING(NUMBER_DATA),
    STRING(STRING_DATA)
};
#undef STRING
